import {
	Activity,
	AlertCircle,
	Calendar,
	Check,
	ChevronRight,
	Circle,
	Command,
	CreditCard,
	DollarSign,
	Edit,
	Home,
	Inbox,
	Loader2,
	type LucideIcon,
	MoreHorizontal,
	Plus,
	Settings,
	Terminal,
	Trash,
	Users,
	X,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
	logo: Command,
	spinner: Loader2,
	home: Home,
	users: Users,
	inbox: Inbox,
	calendar: Calendar,
	settings: Settings,
	add: Plus,
	delete: Trash,
	edit: Edit,
	more: MoreHorizontal,
	check: Check,
	close: X,
	chevronRight: ChevronRight,
	circle: Circle,
	dollarSign: DollarSign,
	creditCard: CreditCard,
	activity: Activity,
	terminal: Terminal,
	alertCircle: AlertCircle,
};
