/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ExampleShowcaseRouteImport } from './routes/example/showcase'
import { Route as ChatThreadIdRouteImport } from './routes/chat/$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AboutYouRouteImport } from './routes/about/you'
import { Route as AboutTestRouteImport } from './routes/about/test'
import { Route as AboutMeRouteImport } from './routes/about/me'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleShowcaseRoute = ExampleShowcaseRouteImport.update({
  id: '/example/showcase',
  path: '/example/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutYouRoute = AboutYouRouteImport.update({
  id: '/about/you',
  path: '/about/you',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTestRoute = AboutTestRouteImport.update({
  id: '/about/test',
  path: '/about/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about/me',
  path: '/about/me',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/about/me': typeof AboutMeRoute
  '/about/test': typeof AboutTestRoute
  '/about/you': typeof AboutYouRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/example/showcase': typeof ExampleShowcaseRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about/me': typeof AboutMeRoute
  '/about/test': typeof AboutTestRoute
  '/about/you': typeof AboutYouRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/example/showcase': typeof ExampleShowcaseRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/about/me': typeof AboutMeRoute
  '/about/test': typeof AboutTestRoute
  '/about/you': typeof AboutYouRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/example/showcase': typeof ExampleShowcaseRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/about/me'
    | '/about/test'
    | '/about/you'
    | '/api/chat'
    | '/chat/$threadId'
    | '/example/showcase'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about/me'
    | '/about/test'
    | '/about/you'
    | '/api/chat'
    | '/chat/$threadId'
    | '/example/showcase'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/about/me'
    | '/about/test'
    | '/about/you'
    | '/api/chat'
    | '/chat/$threadId'
    | '/example/showcase'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  AboutMeRoute: typeof AboutMeRoute
  AboutTestRoute: typeof AboutTestRoute
  AboutYouRoute: typeof AboutYouRoute
  ApiChatRoute: typeof ApiChatRoute
  ExampleShowcaseRoute: typeof ExampleShowcaseRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/showcase': {
      id: '/example/showcase'
      path: '/example/showcase'
      fullPath: '/example/showcase'
      preLoaderRoute: typeof ExampleShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/you': {
      id: '/about/you'
      path: '/about/you'
      fullPath: '/about/you'
      preLoaderRoute: typeof AboutYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/test': {
      id: '/about/test'
      path: '/about/test'
      fullPath: '/about/test'
      preLoaderRoute: typeof AboutTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/me': {
      id: '/about/me'
      path: '/about/me'
      fullPath: '/about/me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  AboutMeRoute: AboutMeRoute,
  AboutTestRoute: AboutTestRoute,
  AboutYouRoute: AboutYouRoute,
  ApiChatRoute: ApiChatRoute,
  ExampleShowcaseRoute: ExampleShowcaseRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
