/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExampleShowcaseRouteImport } from './routes/example/showcase'
import { Route as AboutYouRouteImport } from './routes/about/you'
import { Route as AboutTestRouteImport } from './routes/about/test'
import { Route as AboutMeRouteImport } from './routes/about/me'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleShowcaseRoute = ExampleShowcaseRouteImport.update({
  id: '/example/showcase',
  path: '/example/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutYouRoute = AboutYouRouteImport.update({
  id: '/about/you',
  path: '/about/you',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTestRoute = AboutTestRouteImport.update({
  id: '/about/test',
  path: '/about/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about/me',
  path: '/about/me',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/me': typeof AboutMeRoute
  '/about/test': typeof AboutTestRoute
  '/about/you': typeof AboutYouRoute
  '/example/showcase': typeof ExampleShowcaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about/me': typeof AboutMeRoute
  '/about/test': typeof AboutTestRoute
  '/about/you': typeof AboutYouRoute
  '/example/showcase': typeof ExampleShowcaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/me': typeof AboutMeRoute
  '/about/test': typeof AboutTestRoute
  '/about/you': typeof AboutYouRoute
  '/example/showcase': typeof ExampleShowcaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/me'
    | '/about/test'
    | '/about/you'
    | '/example/showcase'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about/me' | '/about/test' | '/about/you' | '/example/showcase'
  id:
    | '__root__'
    | '/'
    | '/about/me'
    | '/about/test'
    | '/about/you'
    | '/example/showcase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutMeRoute: typeof AboutMeRoute
  AboutTestRoute: typeof AboutTestRoute
  AboutYouRoute: typeof AboutYouRoute
  ExampleShowcaseRoute: typeof ExampleShowcaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/showcase': {
      id: '/example/showcase'
      path: '/example/showcase'
      fullPath: '/example/showcase'
      preLoaderRoute: typeof ExampleShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/you': {
      id: '/about/you'
      path: '/about/you'
      fullPath: '/about/you'
      preLoaderRoute: typeof AboutYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/test': {
      id: '/about/test'
      path: '/about/test'
      fullPath: '/about/test'
      preLoaderRoute: typeof AboutTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/me': {
      id: '/about/me'
      path: '/about/me'
      fullPath: '/about/me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutMeRoute: AboutMeRoute,
  AboutTestRoute: AboutTestRoute,
  AboutYouRoute: AboutYouRoute,
  ExampleShowcaseRoute: ExampleShowcaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
